### ISSUE TITLE
Add api documentation

### ISSUE THREAD

**Issue by bmmunga** [MungaSoftwiz/EcoSortify#31]
Now that we have created the APIs we need to document them and validate the data of incoming requests to our API endpoints against the schemas.
We are going to use Flasgger, the python's Swagger wrapper.

**Comment by Liamhhhhh** [comment]
Why not use [Apidog](https://www.apidog.com/?utm_source=&utm_medium=blogger&utm_campaign=test1)? I am currently using it and it's not bad.

**Comment by bmmunga** [comment]
Yeah? I might as well check it out?

Does it have good integrations with flask? I'm currently encountering issues with flassger. I created the APIs and set us swagger but my app can't really show the APIs. 
Exact output: No operations defined in spec!

I'll set up a draft PR right away @Liamhhhhh
